name: Custom Fork Build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Assemble the project
        run: ./gradlew assemble
        
      - name: Run the tests
        run: ./gradlew test
        
      - name: Run build in a subdirectory
        working-directory: another-build
        run: ./gradlew build shadowJar
        
      - name: Get build artifact ready
        run: mkdir staging && cp build/libs/*.jar staging

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Custom Fork Build
          path: staging
